services:
  postgres:
    image: postgres:16-alpine
    container_name: lms_postgres
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lms_user -d lms_db"]
      interval: 5s
      retries: 5
    networks:
      - lms_network
    
  redis:
    image: redis:7-alpine
    container_name: lms_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
    networks:
      - lms_network

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: lms_php
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - lms_network
  
  nginx:
    image: nginx:1.25-alpine
    container_name: lms_nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/backend
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - lms_network

  minio:
    image: minio/minio:latest
    container_name: lms_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ruddy
      MINIO_ROOT_PASSWORD: ruddy3099
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - lms_network
  
  mailpit:
    image: axllent/mailpit:latest
    container_name: lms_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - lms_network

networks:
  lms_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  minio_data: